version: '3'
services:
  frontend:
    image: mini-mailgun/bundle
    entrypoint: ./frontend.py
    ports:
      - "5080:5000"
    volumes:
      - '.:/mailq'

  sender-1:
    image: mini-mailgun/bundle
    entrypoint: ./sender.py
    environment:
      RETRY_INTERVAL: 3
      SHARD: 1/2
      SMTP_PORT: 5000
      STATIC_MX_CONFIG: a.com:smtp-a,b.com:smtp-b
    volumes:
      - '.:/mailq'

  sender-2:
    image: mini-mailgun/bundle
    entrypoint: ./sender.py
    environment:
      RETRY_INTERVAL: 3
      SHARD: 2/2
      SMTP_PORT: 5000
      STATIC_MX_CONFIG: a.com:smtp-a,b.com:smtp-b
    volumes:
      - '.:/mailq'

  smtp-a:
    image: mini-mailgun/bundle
    entrypoint: ./smtpstub.py
    environment:
      DOMAIN: a.com
    volumes:
      - '.:/logs'

  smtp-b:
    image: mini-mailgun/bundle
    entrypoint: ./smtpstub.py
    environment:
      DOMAIN: b.com
    volumes:
      - '.:/logs'
