version: '3'
services:
  frontend:
    image: mini-mailgun/bundle
    entrypoint: ./frontend.py
    ports:
      - "5080:5000"
    volumes:
      - '.:/mailq'

  sender:
    image: mini-mailgun/bundle
    entrypoint: ./sender.py
    volumes:
      - '.:/mailq'

  smtpstub:
    image: mini-mailgun/bundle
    entrypoint: ./smtpstub.py
    ports:
      - "5025:5000"
    volumes:
      - '.:/logs'
